# Generated by Django 2.0.7 on 2018-08-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20180814_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'A lot of users'},
        ),
    ]
