# Generated by Django 2.0.7 on 2018-08-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productinorder_mukola'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='mukola',
            new_name='калян',
        ),
    ]
