# Generated by Django 2.0.7 on 2018-08-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180824_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='калян',
        ),
    ]
